### ISSUE TITLE
image can't be centered

### ISSUE THREAD

**Issue by Gavin-jy** [alangrainger/obsidian-image-captions#1]
I found a problem that my settings for centering the pics will lose their function if I use this plugin.
here are my snippets for centering the image:

```
.center-image :is(.markdown-preview-view,.markdown-rendered) img:not([class*="emoji"]) {
  margin-left: auto;
  margin-right: auto;
}

.center-image .print :is(.markdown-preview-view,.markdown-rendered) img:not([class*="emoji"]) {
  display: block;
}

.center-image .view-content img:not([class*="emoji"]) {
  cursor: zoom-in;
  display: block;
  margin-left: auto !important;
  margin-right: auto !important;
}
```

I try to use the above snippet into your plugin's CSS but failed. I don't know how to make the setting for images keep working if I load your plugin into my obsidian. And I don't know whether or not it's a bug or limits of my knowledge.

**Comment by alangrainger** [comment]
You just need to target the new captioned image:

```css
.image-captions-figure {
  margin-left: auto;
  margin-right: auto;
}
```
