### ISSUE TITLE
Default Caption is hidden in image

### ISSUE THREAD

**Issue by ckaiser79** [alangrainger/obsidian-image-captions#10]
Hello,

I am using image captions 1.0.7. By default the caption is hidden in the image (see the first example):

![default](https://user-images.githubusercontent.com/11504021/232408956-9d2dd9e9-f549-4127-af68-97bd761563df.png)

When I apply this CSS snippet, it works perferctly:

```css
.image-captions-caption { margin-top: 5px; margin-bottom: 5px; text-align: left; }
```

![image](https://user-images.githubusercontent.com/11504021/232409204-0ede84e9-76e3-4b45-84d7-9ca9d551a4e4.png)

This is not a big issue, but some kind of confusing, when using the plugin the first time and realise there is css code to write first. Maybe this is an incompatiblity with another Plugin, here is the list I am using:

![plugin 1-2](https://user-images.githubusercontent.com/11504021/232409651-d4725bb0-92d0-4931-a958-b7c469537659.png)

![image](https://user-images.githubusercontent.com/11504021/232409736-ab13f26a-9435-4e44-ba75-3253a02116f9.png)

Hope it helps
Christian

**Comment by ckaiser79** [comment]
And forgot one plugin: "Paste Rename Image 1.0.3"

**Comment by alangrainger** [comment]
For all plugins (not just this one), the only safe way to test for an issue is in the Sandbox vault, which you can access from the Help menu.

If the problem occurs in the sandbox vault, then it will be a problem with the plugin. If the problem doesn't occur in the sandbox vault then it must be something in your specific configuration which is causing the issue.

As this issue does not appear in the sandbox vault, it is unique and custom to your setup, therefore adding custom CSS to address it is the correct solution.

**Comment by ckaiser79** [comment]
Thanks for the explanation. I was not aware of the Sandbox.
