### ISSUE TITLE
look weird in minimal theme

### ISSUE THREAD

**Issue by lszddz** [alangrainger/obsidian-image-captions#13]
hi, thanks for your work! But I found it different in minimal theme, it looks kind of weird. Can you fix this?

**Comment by lszddz** [comment]
<img width="510" alt="image" src="https://github.com/alangrainger/obsidian-image-captions/assets/62652085/3361924f-285f-4e62-b4e4-eb34b9a0cfc3">

**Comment by alangrainger** [comment]
Here's the Sandbox vault with Minimal theme - looks perfect to me:

![image](https://github.com/alangrainger/obsidian-image-captions/assets/16197738/b591758e-80fc-4fc5-b12b-3ae2255750b1)

Always test in the Sandbox vault before making a bug report on the Obsidian Forum or for any plugin. You'll want to check your custom CSS snippets other customisations.

**Comment by arpir** [comment]
> <img alt="image" width="510" src="https://user-images.githubusercontent.com/62652085/261901975-3361924f-285f-4e62-b4e4-eb34b9a0cfc3.png">

It looks like the **Minimal Theme Settings** extension cause the problem, I'm experiencing the same thing.

**Comment by alangrainger** [comment]
Here it is with Minimal theme and the Minimal Theme Settings plugin, looks perfect to me:

![image](https://github.com/alangrainger/obsidian-image-captions/assets/16197738/7427e777-7d72-4391-b6ac-d7b5af4fdd54)

![image](https://github.com/alangrainger/obsidian-image-captions/assets/16197738/27683d1b-aaca-49ba-86be-6f711c2d7ace)

**Comment by nazzacode** [comment]
Fust a +1 that I am also having this problem and would be interested in a solution.
