### ISSUE TITLE
how to apply styling?

### ISSUE THREAD

**Issue by JulienVincenot** [alangrainger/obsidian-image-captions#14]
Hi !

I just discovered this cool plugin. I'm just wondering, I'm quite bad at CSS and you don't really give an example of how to apply styling.

I have a CSS snippet containing simply  :

```
img[alt*="center"] {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

I'm not sure how to add those two targets you mention on the plugin page (.image-captions-figure and .image-captions-caption)
so that I can still have my image centered with ![[image.jpeg | "caption text" | center | 300 ]]

Thanks in advance for your help !

Julien

**Comment by alangrainger** [comment]
Please check the closed issues - already answered in #3 :

If you want to center the image, use this CSS:

```css
.image-captions-figure { 
  margin-left: auto; 
  margin-right: auto; 
}
```

**Comment by JulienVincenot** [comment]
I'm sorry I wasn't clear, I wanted it to still be an option, like it was before I added that css snippet :

![[image.jpeg | "caption text" | 300 ]] => default left
![[image.jpeg | "caption text" | center | 300 ]] => centered

even maybe
![[image.jpeg | "caption text" | right | 300 ]] => right

**Comment by alangrainger** [comment]
Ah, I understand. Currently it's not possible to target in this way, as by putting the `|center` into the alt-text area it would then need to be stripped out before displaying.

You are welcome to code it up and submit a pull request. Otherwise if enough people are looking for the same thing, it would be possible for me to add this.

**Comment by HWLND** [comment]
Hello, I'm currently having the same issue. I'm also using a CSS snippet very similar to theirs, to adjust and add other attributes to embedded pictures. Your plugin has been very useful and I quite like the styling of the captions. Have you reconsidered making this a feature or maybe changing how the plugin detects what part of the alt-text is a caption? (maybe using some kind of header or delimiters like caption:"this is an example of a caption"). Thanks a lot for the cool plug-in anyway
