### ISSUE TITLE
Support for delimiters like "obsidian-image-caption"

### ISSUE THREAD

**Issue by TDSrock** [alangrainger/obsidian-image-captions#19]
The delimiter option provided by the plugin you based this one off of has a neat feature to determine a delimiter, which ideally would allow this plugin to play nice with ITS theme's image shifting options.

**Comment by alangrainger** [comment]
Merged into #24

**Comment by alangrainger** [comment]
This has been added in 1.1.2

You can use a custom regex to determine exactly what to parse for the caption, depending on your own preference and vault setup.

In the case of using ITS, the regex should be:

```
^([^|]+)
```
