### ISSUE TITLE
Difference from bicarlsen/obsidian_image_caption

### ISSUE THREAD

**Issue by rinogo** [alangrainger/obsidian-image-captions#2]
Hi! Thanks for this plugin!

This is a fork of https://github.com/bicarlsen/obsidian_image_caption, right? I'm having a hard time seeing how this differs from the original plugin.

In other words, in what situations would I use this plugin over the original?

Thanks!

**Comment by alangrainger** [comment]
a) No it's not a fork.

b) It's functional. The one you quoted doesn't actually work in 1.x. But if it does work for you, then no reason at all, go nuts with the other one.
