### ISSUE TITLE
Captions do not support html (or at least overrule styling)

### ISSUE THREAD

**Issue by TDSrock** [alangrainger/obsidian-image-captions#26]
First off, thanks for the recent update, I've been going back to now include captions where I originally wanted them. This is awesome.

While adding a few captions it irked me that the caption text is left aligned. So I thought I'd just write a little bit HTML and override the styling. This however doesn't seem to be playing nice. Any of the other tricks I am aware of also failed.

Is this a misuse on my part (or a incompatibility caused by my theme?)

Here was my testing scenario:

```
![[Pasted image 20230722210007.png | <p style="text-align:center;">Needs replacing</p> | center hs-med]] 
 <p style="text-align:center;">Needs replacing</p> 
 ```
 
 Where the pasted image can really be anything at random. 
 The second line is simply here to check what the results normally would be.
 
 
![image](https://github.com/user-attachments/assets/fc7d7ea1-2333-4708-b913-fc7afe860ae0)

The appearance in my obsidian vault.

If there are other ways to alter the styling that I should try, please lets try those first. I would love to have a bit more control over how the content in the captions appear.

**Comment by alangrainger** [comment]
To style the captions, you should use the CSS styles as per the docs:

https://github.com/alangrainger/obsidian-image-captions?tab=readme-ov-file#styling

Target `.image-captions-caption` and style it however you please (e.g. `text-align: center;`)

**Comment by alangrainger** [comment]
Sorry - this is my fault - I didn't add the CSS file to yesterday's update. That's embarrassing!

**Comment by alangrainger** [comment]
This is now fixed in 1.1.3 - please update and it should be centered again. Sorry about that! :grimacing:

**Comment by alangrainger** [comment]
I'd suggest you use ITS theme's built-in image captions setting, rather than this plugin, as they clearly don't work well together.

ITS settings:

![image](https://github.com/user-attachments/assets/70a65009-f99e-416c-be70-7c772b3de877)

**Comment by TDSrock** [comment]
Oh I was unaware, this must have been added in the somewhere between when I looked for this originally and now. Or it just happened to miss my eye. Thanks, I'll give that a shot. I do like the general styling you held with your plugin.
