### ISSUE TITLE
Not rendering with obsidian publish

### ISSUE THREAD

**Issue by epilliat** [alangrainger/obsidian-image-captions#27]
Thanks you for this great puggin. The captions do however not render when I publish my notes with obsidian publishing. Is it possible to correct this in a next version ?

**Comment by alangrainger** [comment]
I don't believe Obsidian Publish supports custom plugins, so there's not much you can do here sorry.

Your best bet would be to use a method supported by Obsidian's built-in functions, for example using callouts as [in this thread](https://forum.obsidian.md/t/adding-caption-to-images/16431/26?u=alang):

```
> [!tip] ![[my_figure.png]]
> *This is the caption* 
```
