### ISSUE TITLE
Make % syntax to be optional. 

### ISSUE THREAD

**Issue by xRyul** [alangrainger/obsidian-image-captions#34]
Anything between | and % becomes a caption.

Please make this optional via the toggle.

**Comment by alangrainger** [comment]
Obsidian doesn't allow you to resize by percentage though, so what do you mean?

https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#External+images

**Comment by xRyul** [comment]
It does via custom snippets. I see you had similar issue in 2023, but there it was more general, where container didn't stick to whole size.

**Comment by alangrainger** [comment]
In that case - you could use the same custom snippets to target the `<figcaption>` element of an image resized by your custom snippets, and set it to `display:none;`.

The caption is provided from Obsidian itself, not from this plugin, so I'm not planning on changing the way Obsidian identifies the caption + size of an image to satisfy this kind of custom use-case.

**Comment by xRyul** [comment]
But why force user to use % if it doesn't even work as intended?

From your readme it says, % acts just as a placeholder to use filename as a caption? But in reality it is possible to put anything you want in there. Any string in between still gets rendered. Toggle to make it optional at least would disable it completely.
