### ISSUE TITLE
Captions do not support percentage widths

### ISSUE THREAD

**Issue by jvsteiner** [alangrainger/obsidian-image-captions#9]
I had a transclusion that was like this:

`![[filename.png|100%]]`  which actually works to make it 100% width (nice for mobile, and other typesetting cases

I wanted to add a caption using this plugin, and tried:

`![[filename.png|caption text|100%]]`  but it doesn't work with the %.  The caption turned up as "caption text|100%"  and the width was ignored.  This is syntax that is generally supported in Obsidian, and I suggest that this plugin should support it as well.

Thanks!

**Comment by jvsteiner** [comment]
It does support it, compare:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1165328/234047003-ef0f40dd-1aba-4d88-825f-b94051f83453.png">

Where I gave the image a 500px width, and it is clipped when I make the window small, vs:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/1165328/234047230-3945638d-b25c-4a4a-896d-97d02eb7220d.png">

Where it scales to the available size in the small window.

These were taken with the caption plugin disabled.

With the plugin enabled, it becomes:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1165328/234048008-e2b629d9-fb8e-43dd-bcfb-5e0cd7b00a68.png">

The caption, which is out of view, just says "A Cat"

and

<img width="237" alt="image" src="https://user-images.githubusercontent.com/1165328/234048146-ceb6f4a1-c188-4436-8a93-f9f6019d7d87.png">

Where you can see that the image scales properly, but the Caption includes the "|100%" characters, as if they should be part of the caption.

Make sense?

**Comment by jvsteiner** [comment]
My original report was wrong, in that I said that it did not support it - it seems that it does, but the caption text is wrong.  Sorry for the error and confusion.

**Comment by alangrainger** [comment]
I'm a bit confused by the report, sorry! 

If you are saying that percentage scales are supported, can you please take a screenshot of the Sandbox Vault with no plugins, showing that percentages are supported by Obsidian by default?

**Comment by jvsteiner** [comment]
I apologize.  I had been using 100%, and it didn't occur to me that it might be the default.  So nevermind - it seems my issue is moot.
